version: '3.8'
services:
  author:
    image: aem
    build:
      context: ./docker
    ports:
      - 4502:8080
      - 5402:58242
    volumes:
      - aem-author-spa:/aem/crx-quickstart
    environment:
      - AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,local
      - AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58242
  publish:
    image: aem
    ports:
      - 4503:8080
      - 5403:58242
    volumes:
      - aem-publish-spa:/aem/crx-quickstart
    environment:
      - AEM_RUNMODE=-Dsling.run.modes=publish,crx3,crx3tar,local
      - AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58242
volumes:
  aem-author-spa:
  aem-publish-spa: